appVersion: apps/v1
kind: Deployment
metadata:
  name: camera-deployment
spec:
  selector:
    matchLabels:
      app: camera
  replicas: 1
  template:
    metadata:
      labels:
        app: camera
    spec:
      containers:
      - name: camera
        image: camera:v1
        ports:
          containerPort: 
        env:
        - name:
          value:
