apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-deployment
spec:
  selector:
    matchLabels:
      app: camera
  replicas: 1
  template:
    metadata:
      labels:
        app: camera
    spec:
      containers:
      - name: camera
        image: hsiungc/camera:v1
        volumeMounts:
        - name: cam-0
          mountPath: /dev/video0
        securityContext:
          priviledged: true
      volumes:
      - name: cam-0
        hostPath:
      	  path: /dev/video0
