appVersion: apps/v1
kind: Deployment
metadata:
  name: camera-deployment
spec:
  selector:
    matchLabels:
      app: camera
  replicas: 1
  template:
    metadata:
      labels:
        app: camera
    spec:
      containers:
      - name: camera
        image: camera:v1
        ports:
          containerPort: 80
        env:
        - name: # BRING in info/networking for usb camera
          value:
        - name: LOCAL_MQTT_HOST
          value: mosquitto-service