apiVersion: apps/v1
kind: Deployment
metadata:
  name: fowarder-deployment
spec:
  selector:
    matchLabels:
      app: forwarder
  replicas: 1
  template:
    metadata:
      labels:
        app: forwarder
    spec:
      containers:
      - name: forwarder
        image: hsiungc/mqtt_forwarder:v1
        env:
        - name: AWS_IP
          value: "10.43.70.78"