apiVersion: apps/v1
kind: Deployment
metadata:
  name: forwarder-deployment
spec:
  selector:
    matchLabels:
      app: forwarder
  replicas: 1
  template:
    metadata:
      labels:
        app: forwarder
    spec:
      containers:
      - name: forwarder
        image: hsiungc/mqtt_forwarder:v2
        env:
        - name: AWS_IP
          value: "54.90.54.177"
        - name: NODEPORT
          value: "30145"
