apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-deployment
spec:
  selector:
    matchLabels:
      app: logger
  replicas: 1
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger
        image: hsiungc/mqtt_logger:v1
#        ports:
#        - containerPort: 1883
