apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-deployment
spec:
  selector:
    matchLabels:
      app: processor
  replicas: 1
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
      - name: processor
        image: hsiungc/mqtt_processor:v1